//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnlineExaminationSystemEntities : DbContext
    {
        public OnlineExaminationSystemEntities()
            : base("name=OnlineExaminationSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblClass> tblClasses { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
        public virtual DbSet<tblSubject> tblSubjects { get; set; }
        public virtual DbSet<tblQuestion> tblQuestions { get; set; }
        public virtual DbSet<tblfinalResult> tblfinalResults { get; set; }
    
        public virtual int deleteQuestion(Nullable<int> questionID)
        {
            var questionIDParameter = questionID.HasValue ?
                new ObjectParameter("questionID", questionID) :
                new ObjectParameter("questionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteQuestion", questionIDParameter);
        }
    
        public virtual ObjectResult<DoSignUP_Result> DoSignUP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoSignUP_Result>("DoSignUP");
        }
    
        public virtual ObjectResult<string> GetSubj()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetSubj");
        }
    
        public virtual ObjectResult<Login_Result> Login()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Login_Result>("Login");
        }
    
        public virtual ObjectResult<SPLogin_Result> SPLogin(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPLogin_Result>("SPLogin", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<getClass_Result> getClass()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getClass_Result>("getClass");
        }
    
        public virtual int DeleteClass(Nullable<int> classID)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteClass", classIDParameter);
        }
    
        public virtual int deleClass(Nullable<int> classID)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleClass", classIDParameter);
        }
    
        public virtual ObjectResult<GetSubject_Result> GetSubject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubject_Result>("GetSubject");
        }
    
        public virtual ObjectResult<SearchClass_Result> SearchClass(string className)
        {
            var classNameParameter = className != null ?
                new ObjectParameter("className", className) :
                new ObjectParameter("className", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchClass_Result>("SearchClass", classNameParameter);
        }
    
        public virtual ObjectResult<deleteSubject_Result> deleteSubject(Nullable<int> subjectID)
        {
            var subjectIDParameter = subjectID.HasValue ?
                new ObjectParameter("SubjectID", subjectID) :
                new ObjectParameter("SubjectID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<deleteSubject_Result>("deleteSubject", subjectIDParameter);
        }
    
        public virtual int deletesubj(Nullable<int> subjectID)
        {
            var subjectIDParameter = subjectID.HasValue ?
                new ObjectParameter("SubjectID", subjectID) :
                new ObjectParameter("SubjectID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletesubj", subjectIDParameter);
        }
    
        public virtual int spQuestions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spQuestions");
        }
    
        public virtual ObjectResult<Questions_Result> Questions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Questions_Result>("Questions");
        }
    
        public virtual ObjectResult<ddlSubject_Result> ddlSubject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ddlSubject_Result>("ddlSubject");
        }
    
        public virtual ObjectResult<spSubject_Result> spSubject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSubject_Result>("spSubject");
        }
    
        public virtual int DeleteClass1(Nullable<int> classId)
        {
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteClass1", classIdParameter);
        }
    
        public virtual int removeClass(Nullable<int> classId)
        {
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("classId", classId) :
                new ObjectParameter("classId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removeClass", classIdParameter);
        }
    
        public virtual ObjectResult<string> stdsubject(Nullable<int> subjctID)
        {
            var subjctIDParameter = subjctID.HasValue ?
                new ObjectParameter("subjctID", subjctID) :
                new ObjectParameter("subjctID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("stdsubject", subjctIDParameter);
        }
    
        public virtual ObjectResult<getSbjs_Result> getSbjs(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSbjs_Result>("getSbjs", idParameter);
        }
    
        public virtual ObjectResult<QuestionPaper_Result> QuestionPaper(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QuestionPaper_Result>("QuestionPaper", idParameter);
        }
    
        public virtual ObjectResult<getUserName_Result> getUserName(Nullable<int> loginId)
        {
            var loginIdParameter = loginId.HasValue ?
                new ObjectParameter("loginId", loginId) :
                new ObjectParameter("loginId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUserName_Result>("getUserName", loginIdParameter);
        }
    
        public virtual ObjectResult<getResult_Result> getResult()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getResult_Result>("getResult");
        }
    
        public virtual ObjectResult<aminlogin_Result> aminlogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<aminlogin_Result>("aminlogin");
        }
    
        public virtual ObjectResult<Searchsubject_Result> Searchsubject(string subjectName)
        {
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("subjectName", subjectName) :
                new ObjectParameter("subjectName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Searchsubject_Result>("Searchsubject", subjectNameParameter);
        }
    
        public virtual ObjectResult<Searchsubjectpaper_Result> Searchsubjectpaper(string subjectName)
        {
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("subjectName", subjectName) :
                new ObjectParameter("subjectName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Searchsubjectpaper_Result>("Searchsubjectpaper", subjectNameParameter);
        }
    }
}
